### ISSUE TITLE
Provide example administration profile for managing commands

### ISSUE THREAD

**Issue by ericholtam** [facebookincubator/sado#6]
The ReadMe mentions the ability to manage the approved commands (`If you don't have a sado profile installed by your administrator`) , but there's no example profile or details on how to generate a management profile for it - domain, keys, etc. Please expand on that.

Also make it clearer that If the profile exists, does that mean manual additions of commands is blocked?

**Comment by kilpatds** [comment]
Fixed via PR #10 ... but I had to reset the repo to fix a bug I created with the sync from internal to github. Please nuke your repo and re-pull it.
