### ISSUE TITLE
Command-line binary list-commands not working

### ISSUE THREAD

**Issue by ericholtam** [facebookincubator/sado#7]
Using the SadoBinary, after running `SadoBinary add-command newer_command "touch file"` I see in `~/Library/Preferences/SadoBinary.plist` an entry is generated:

```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ValidCommands</key>
	<dict>
		<key>newer_command</key>
		<array>
			<string>touch file</string>
		</array>
	</dict>
</dict>
</plist>
```

But when issuing `SadoBinary list-commands` I get:
```               
No available commands.
```

**Comment by kilpatds** [comment]
My knee-jerk right now is that this, and issue #9 are dups? I don't have a system immediately at-hand that DOESN'T have the configuration profile handy, but when I added a command I get the preferences plist (that will then be ignored) with all of the configured commands, PLUS the one I added.  If I add a 2nd command, I get the plist with all the configured commands plus the new one I added, but not including the first.

The implementation of adding a command is "grab the config, add the command, write out the config", and not showing it is consistent with "grabbing the config" not correctly reading the newly created config.

```
    @Argument var name: String
    @Argument(parsing: .unconditionalRemaining)
    var command: [String]
    mutating func run() throws {
      var commandList: CommandList = getCommandList() ?? [:]
      commandList[name] = command
      setCommandList(commandList)
    }
 ```

Ah, compare set to get. Notice that the bundlename isn't the same. It should be writing out to ~/Library/Preferences/com.facebook.cpe.Sado.plist instead.
