### ISSUE TITLE
SadoBinary overwrites entire file ~/Library/Preferences/SadoBinary.plist on `add-command`

### ISSUE THREAD

**Issue by ericholtam** [facebookincubator/sado#8]
I added a command using `SadoBinary add-command newer_command "touch file"` and could see it was listed in `~/Library/Preferences/SadoBinary.plist`

***SadoBinary.plist***
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ValidCommands</key>
	<dict>
		<key>newer_command</key>
		<array>
			<string>touch file</string>
		</array>
	</dict>
</dict>
</plist>
```

After trying to add a second command with `SadoBinary add-command newest_command "rm file"` the file contents are now just the last command, not both:

***SadoBinary.plist***
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ValidCommands</key>
	<dict>
		<key>newest_command</key>
		<array>
			<string>rm file</string>
		</array>
	</dict>
</dict>
</plist>
```

**Comment by kilpatds** [comment]
Yes, but that's not the bug. The bug is that we're not correctly picking up the right profile to add to.

Also a dup of #7
